spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/Ec202110a
        username: postgres
        password: postgres
server:
 servlet:
    context-path: /rakurakusauna 